sudo: required
services:
  - docker

before_install:
  - docker build -t venkatesh1219/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true venkatesh1219/react-test npm test -- --coverage

after_success:
  - docker build -t venkatesh1219/fibonacci-multi-client ./client
  - docker build -t venkatesh1219/fibonacci-multi-server ./server
  - docker build -t venkatesh1219/fibonacci-multi-nginx ./nginx
  - docker build -t venkatesh1219/fibonacci-multi-worker ./worker

# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push them to docker hub
  - docker push venkatesh1219/fibonacci-multi-client
  - docker push venkatesh1219/fibonacci-multi-server
  - docker push venkatesh1219/fibonacci-multi-nginx
  - docker push venkatesh1219/fibonacci-multi-worker

